### ISSUE TITLE
Use functional parameters in Controller creation

### ISSUE THREAD

**Issue by dzlier-gcp** [GoogleCloudPlatform/agones#104]
The constructor for Controller in controller.go is becoming unwieldy and has the potential to be error-prone as more parameters are added.

Go makes use of [functional parameters](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) in a similar way that some other languages use Builders. We should consider doing so as well to help readability as more developers start working on the project.

**Comment by markmandel** [comment]
Any objections to me closing this issue? Looks like the pattern we have now solves this for the moment?

**Comment by markmandel** [comment]
Going to close this, sounds like it's not an issue anymore. 

Please re-open as needed.
