### ISSUE TITLE
Add liveness check to `pkg/gameservers/controller`.

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/agones#116]
[Original Context](https://github.com/googleprivate/agones/pull/98#issuecomment-368082197).

> I don't know if this is possible, but what would determine if this controller is healthy is that the goroutines generated [in this code](https://github.com/GoogleCloudPlatform/agones/blob/master/pkg/gameservers/controller.go#L224) are still running and haven't exited in any way.

**Comment by markmandel** [comment]
@enocom mind if I edit this ticket to include the full details? Just in case anyone else happens to want to pick this up? (Unless you want to expand this out, since I know you had ideas)

**Comment by enocom** [comment]
@markmandel Please do. I think this issue might be good for first-time contributors, too.

**Comment by markmandel** [comment]
Some interesting notes here:
- The health check handler is passed in [here](https://github.com/GoogleCloudPlatform/agones/blob/master/pkg/gameservers/controller.go#L77)
- The actual goroutines are run [in the workerqueue](https://github.com/GoogleCloudPlatform/agones/blob/master/pkg/util/workerqueue/workerqueue.go#L114). so there is likely opportunity to standardise this across anything that uses a workerqueue.

Final thought - for a readiness check, readiness can be turned on as soon as the [WebHook that powers the MutationWebhookConfiguration is ready](https://github.com/GoogleCloudPlatform/agones/blob/master/cmd/controller/main.go#L139)

**Comment by markmandel** [comment]
@enocom did you have some thoughts on how you were thinking of tracking if the goroutines were still active? (or maybe a PR :grin: )

**Comment by enocom** [comment]
I imagine adding a `Registrar`, which in functionality would be similar to a `sync.WaitGroup`. We pass the `Registrar` to anything that starts a `goroutine` and upon starting the `goroutine`, we maybe call `registrar.Inc()` with a corresponding `defer registrar.Dec()` for when the `goroutine` exits. Then the liveness check could simply query the `Registrar` to see if all registered `goroutines` are still running.

Thoughts?

**Comment by markmandel** [comment]
Works for me. Although the Inc() and Dec() would need to be threadsafe. I'm assuming a `sync.RWMutex` ?

**Comment by enocom** [comment]
There's some question of where this responsibility belongs.

Insofar as implementation, `sync.RWMutex` works and maybe even a `sync.Mutex` too. Just depends where the hot paths may be.
