### ISSUE TITLE
Helm package CI

### ISSUE THREAD

**Issue by Kuqd** [GoogleCloudPlatform/agones#153]
copy from another discussion:

For helm we need to have a CI system where we can run lint and package commands
storage (I prefer google cloud storage for this, also we can use github pages or smth else)

Also, we can contribute to kubernetes/charts repo agones helm chart from #149. This repo is a common place to look for helm charts, they provide CI system and 2 repos: https://kubernetes-charts.storage.googleapis.com and https://kubernetes-charts-incubator.storage.googleapis.com

**Comment by fooock** [comment]
For the process to create, package and push to the chart remote storage (github pages, kubernetes chart repo etc) we can make a Helm plugin.

**References**
* https://github.com/viglesiasce/helm-gcs
* https://github.com/technosophos/helm-github

Maybe, I like the idea of contribute to the kubernetes/charts repo. As @Kuqd says
* Is a common place to look for Helm charts
* CI system
* Two repos 

They provide a complete guide of [contributing](https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md)

**Comment by Kuqd** [comment]
Should we close ? I feel like we have already good helm integration, WDYT ?

**Comment by markmandel** [comment]
I think you are right! I think we can close this. @fooock any objections?

**Comment by fooock** [comment]
Ok, we can close this :+1:

**Comment by markmandel** [comment]
Done!
