### ISSUE TITLE
Google Bot is double posting

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/agones#155]
See, for example, [here](https://github.com/GoogleCloudPlatform/agones/pull/149#issuecomment-375120730) and [here](https://github.com/GoogleCloudPlatform/agones/pull/154#issuecomment-377049447).

**Comment by markmandel** [comment]
I've disabled the webhook for the cla bot for this repository. It may well be already configured at an org level.

Let's see how it goes.

**Comment by Kuqd** [comment]
Seems good since then should we close ?

**Comment by markmandel** [comment]
Seems that way! Let's close it!
