### ISSUE TITLE
Add .helmignore to Helm chart

### ISSUE THREAD

**Issue by fooock** [GoogleCloudPlatform/agones#168]
To ignore common files like in [this]( https://github.com/kubernetes/charts/blob/master/stable/aerospike/.helmignore) chart

**Comment by markmandel** [comment]
Just so I understand this properly - what is the exact purpose of a .helmignore file? Where would it go in the repo? @enocom I think you mentioned this as well. I couldn't find any specific docs on this other than this [single reference](https://docs.helm.sh/helm/#helm-create).

**Comment by markmandel** [comment]
Sorry, I got this wrong, it was @Kuqd who mention this in chat yesterday.

**Comment by Kuqd** [comment]
There is nothing to ignore so far. Should we close and reopen if required?

**Comment by alexandrem** [comment]
I guess it wouldn't hurt to add the default ignore file generated by helm itself:

```
# Patterns to ignore when building packages.
# This supports shell glob matching, relative path matching, and
# negation (prefixed with !). Only one pattern per line.
.DS_Store
# Common VCS dirs
.git/
.gitignore
.bzr/
.bzrignore
.hg/
.hgignore
.svn/
# Common backup files
*.swp
*.bak
*.tmp
*~
# Various IDEs
.project
.idea/
*.tmproj
```
