### ISSUE TITLE
Move Deployment in install script out of v1beta1

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#173]
Somehow I managed to make the `Deployment` as a `extensions/v1beta1` deployment, which has since been deprecated. 

https://github.com/GoogleCloudPlatform/agones/blob/master/install/helm/agones/templates/controller.yaml

It should really be a `apps/v1` `Deployment` instead.
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by dzlier-gcp** [comment]
Is the helm installation tested on Linux? Getting an error when following the instructions there. I'm deleting my cluster and recreating just in case it's out of date.

**Comment by dzlier-gcp** [comment]
```Error: release my-release failed: Namespace "" is invalid: metadata.name: Required value: name or generateName is required```

**Comment by markmandel** [comment]
Yep, I run on Linux all day long.

**Comment by dzlier-gcp** [comment]
Hmm, getting the same error when trying on my windows laptop. May be something about my cluster, will keep looking into it.

**Comment by Kuqd** [comment]
could you send the full logs and the command you're trying ?
