### ISSUE TITLE
gometalinter fails

### ISSUE THREAD

**Issue by fooock** [GoogleCloudPlatform/agones#181]
When I execute the task `make test`, it fails when reaches the linter task

If I open a shell using the tasks `make shell` and execute the command `/root/gen-lint-exclude.sh && gometalinter --config .exclude.gometalinter.json --deadline 100s -t --skip vendor ./...` inside it, the output is:
```
WARNING: deadline exceeded by linter errcheck (try increasing --deadline)
WARNING: deadline exceeded by linter unconvert (try increasing --deadline)
WARNING: deadline exceeded by linter interfacer (try increasing --deadline)
WARNING: deadline exceeded by linter megacheck (try increasing --deadline)
WARNING: deadline exceeded by linter maligned (try increasing --deadline)
WARNING: deadline exceeded by linter gocyclo (try increasing --deadline)
WARNING: deadline exceeded by linter varcheck (try increasing --deadline)
WARNING: deadline exceeded by linter structcheck (try increasing --deadline)
WARNING: deadline exceeded by linter deadcode (try increasing --deadline)
```
The exit code is
```bash
$ echo $?
2
```
My current OS is Windows10

**Comment by markmandel** [comment]
What happens if you extend the deadline on the linker? `--deadline=5m` for example?

**Comment by fooock** [comment]
Same error
```
docker run --rm -v /d/Projects/go/src/agones.dev/agones/build//.config/gcloud:/root/.config/gcloud -v ~/.kube:/root/.kube -v /d/Projects/go/src/agones.dev/agones:/go/src/agones.dev/agones -w /go/src/agones.dev/agones  agones-build:e52ce865fb bash -c \
        "/root/gen-lint-exclude.sh && gometalinter --config .exclude.gometalinter.json --deadline 5m -t --skip vendor ./..."
Makefile:136: recipe for target 'lint' failed
make: *** [lint] Error 2
```

**Comment by markmandel** [comment]
I don't see any error, so what is it the same error, or did something else fail?

**Comment by EricFortin** [comment]
Silly question, what kind of hardware do you have @fooock ? Gometalinter is kind of heavy and was slowing my system down even though I have a Core i5 7th gen in my laptop.

**Comment by markmandel** [comment]
Yeah, I find gometalinter slows down my machine as well something terrible.

We may want to be more generous on the timeout :confused:

**Comment by EricFortin** [comment]
You could also try to add `--disable-all -E errcheck` to run a single linter to ensure you can at least run one successfully. I didn't test on windows since we run this in the build image.

**Comment by fooock** [comment]
@EricFortin if I add these lines the exit is successful
```
root@50e1f8589e8c:/go/src/agones.dev/agones# /root/gen-lint-exclude.sh && \
    gometalinter --disable-all \
    -E errcheck \
    --config .exclude.gometalinter.json \
    --deadline 100s -t --skip vendor ./...
root@50e1f8589e8c:/go/src/agones.dev/agones# echo $?
0
```

**Comment by markmandel** [comment]
Can we close this issue now?

**Comment by markmandel** [comment]
Due to inactivity, I'll close this issue now. If it is still an issue, please submit a PR with an extension to the timeout deadline.
