### ISSUE TITLE
Integrate a spell and/or grammar check into build system

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#187]
It's super easy to miss misspelled words in our .md documentation files.

It would be great if there was a spellchecker (and maybe even a grammar / documentation helper?) integrated into the build system to ensure the documentation continues to be written well.

We could probably just install [aspell](http://aspell.net) and call it directly.

Or maybe something like [write-good](https://github.com/btford/write-good) - but I don't know if we want to add node to our build images. Maybe there is a go version somewhere? Or an online service? Possibly worth exploring.

**Comment by markmandel** [comment]
There is this docker image, that seems to get updated regularly.
https://hub.docker.com/r/hochzehn/write-good/
Could possibly be integrated into cloud builder and/or used as a make target.

**Comment by Kuqd** [comment]
Started to use locally https://github.com/golangci/golangci-lint which advertise faster (also a lot less memory usage) than gometalinter, looks good so far.

They have an [optional spellchecker]( https://github.com/golangci/golangci-lint#disabled-by-default-linters--e--enable) (https://github.com/client9/misspell).

We could do a two birds one stone here ? Improve lint target and have grammar check.

@markmandel Can you have a look at https://github.com/golangci/golangci-lint and let me know what do you think ?

**Comment by markmandel** [comment]
I think we looked at this a while back as well - for the same reasons. @enocom do you have any thoughts or feelings?

Need to make sure our exclude list still works. I'd also like to add `goimport` testing too.

**Comment by enocom** [comment]
It would be nice to use misspell, especially if we're going to switch to golangci-lint.

**Comment by markmandel** [comment]
I say -- let's do it!

Also linking #237 to this, as it looks like the work crosses between the tickets.
