### ISSUE TITLE
Agones vs Spatial OS

### ISSUE THREAD

**Issue by jehan96** [GoogleCloudPlatform/agones#236]
if you don't mind, i would like to ask how to choose between agones and spatial OS
in term of low server management, security, performance and mitigating cheating..

or they do different things and can be used together?
because i feel like confuse google announce agones but before this already introduce spatial OS to developer..both of them are suppose to be game server, right?

**Comment by markmandel** [comment]
So SpatialOS is a product from the company Improbable that runs Persistent Worlds as a Service - so they are essentially a backend as a service for online, persistent multiplayer worlds. (Disclaimer: I do not work there, but they are a partner to Google Cloud)

Agones is an open source tool for allowing you to run dedicated game servers wherever you can/want to run Kubernetes clusters.

So we do somewhat crossover on some aspects, but in quite different ways, and for different types of groups of developers.

Does that answer you question?

**Comment by markmandel** [comment]
I see a thumbs up! :smile: I'll consider this question answered, and closing now.
