### ISSUE TITLE
Use revive instead of gometalinter

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/agones#237]
Although it might not offer as complete coverage, [revive](https://blog.mgechev.com/2018/05/28/revive-golang-golint-linter/) seems significantly faster than gometalinter with a simpler API. Switching linters might help resolve the gometalinter timeouts we've been seeing in CI.

**Comment by markmandel** [comment]
Should we also explore:
https://github.com/golangci/golangci-lint/

And/or maybe move the actual work over to the hosted service they provide as well? (https://golangci.com) ?

**Comment by enocom** [comment]
I think so, as the timeout failures seems to be common, and it's worth looking at alternatives, even if our linting isn't 100% the same as gometalinter.

**Comment by markmandel** [comment]
Even at the 5 minute timeout - sometimes it just doesn't timeout, and sometimes it's still hits the deadline.

I've had to restart recent builds several times at this point.
