### ISSUE TITLE
Agones on GAE

### ISSUE THREAD

**Issue by jehan96** [GoogleCloudPlatform/agones#238]
can i use agones on google app engine?

because agones works on kubernetes, i believe this thing is something like the "docker"..

**Comment by markmandel** [comment]
Unfortunately, Agones will likely never work with Google App Engine.

App Engine is a very opinionated system that is built to run and scale stateless systems (which dedicated game servers are not - they have in memory state when players are playing on them). There is also no compatible layer to the extension mechanisms that Kubernetes provides that Agones is built on top of.

If you are interested in learning more about the various tradeoffs of different systems provided by Google Cloud (including App Engine and Kubernetes), you may find the following resource useful:

- [Choosing the right compute option in GCP: a decision tree](https://cloudplatform.googleblog.com/2017/07/choosing-the-right-compute-option-in-GCP-a-decision-tree.html)
- [GCP Podcast - #2 Compute as a Continuum](https://www.gcppodcast.com/post/episode-2-compute-as-a-continuum/) (A few years old, but much of it still holds true)

Does that answer your question?

**Comment by markmandel** [comment]
I see a thumbs up here too :smile: so closing this question as well.

**Comment by jehan96** [comment]
i believe this already close..
and sorry to comment again..but i believe no need to reopen..just want to confirm..
(because i a little bit confuse between google compute engine and google kubernetes engine)

so, agones will not run on google app engine, okay i understand that...
so if i want to use agones for my game..which google cloud platform product should i choose?
gke or gce?

sorry for the trouble..

**Comment by markmandel** [comment]
You want to be using GKE
https://cloud.google.com/gke

**Comment by jehan96** [comment]
okay thanks
