### ISSUE TITLE
helm image tag

### ISSUE THREAD

**Issue by Kuqd** [GoogleCloudPlatform/agones#248]
Why do we bump the tag in the default value file before the release ?

Today it's already 0.3.0 but no image exits so if you follow the instruction in the README you get a deployment that is not working.

I would prefer to bump that version only once it's release and add a step in the release todo list. What do you think ?

/cc @markmandel

**Comment by markmandel** [comment]
Curious - which README are you looking at? The [Helm Install](https://github.com/GoogleCloudPlatform/agones/blob/master/install/helm/README.md) states to:

> Download the latest agones-install zip from the releases archive.

(Although it definitely could be clearer about actually unzipping it! :blush: )

My opinion is: if the `master` branch is expected to be able to install the previous release from, then we can never develop new things against it, as users are relying on it - and we are stuck. By incrementing the base version in Helm in master, we push users to where they should be getting the supported install versions from - either the release archives, or if they want to clone the repo, then checkout a release branch.

If there is confusion on this, we should update our documentation to be clearer.

**Comment by Kuqd** [comment]
ok I see , I think what confuses me is the `cd install/helm/` it should instead state `curl` then `unzip` then `cd`
