### ISSUE TITLE
Tutorial fails @ Step 5 due to RBAC issues if you have capital letters in your gcloud account name

### ISSUE THREAD

**Issue by CrimsonZen** [GoogleCloudPlatform/agones#282]
In the guide at https://github.com/GoogleCloudPlatform/agones/blob/master/install/README.md#setting-up-a-google-kubernetes-engine-gke-cluster, I ran this line to set up RBAC stuff:

```
kubectl create clusterrolebinding cluster-admin-binding \
  --clusterrole cluster-admin --user `gcloud config get-value account`
```

Then, I moved onto the `kubectl apply` step, which failed. Output included this:

```
...
validatingwebhookconfiguration "agones-validation-webhook" configured
mutatingwebhookconfiguration "agones-mutation-webhook" configured
secret "agones-manual-cert" unchanged
Error from server (Forbidden): error when creating "https://github.com/GoogleCloudPlatform/agones/raw/release-0.2.0/install/yaml/install.yaml": clusterroles.rbac.authorization.k8s.io "agones-controller" is forbidden: attempt to grant extra privileges:
...
```

Turns out, the `gcloud config get-value account` substitution in Step 4 will return a lowercase version of your current user, which causes the subsequent `kubectl apply` step to fail if your "actual username" has uppercase letters in it.  (My username is `CrimsonZen@`, but the substitution offered `crimsonzen@`.)

This thread helped me diagnose the problem: https://github.com/coreos/prometheus-operator/issues/357

I'm very much a kubernetes newbie, but I figured I'd call this out as being a potential hazard during setup if you follow the tutorial.

**Comment by markmandel** [comment]
Oh that's interesting! Good find!

I bet this means there issues across lots of projects that use this step!
