### ISSUE TITLE
Agones helm repo

### ISSUE THREAD

**Issue by Kuqd** [GoogleCloudPlatform/agones#285]
We could setup a chart repository to streamline installation.

See:
https://github.com/kubernetes/helm/blob/master/docs/chart_repository.md

Possible options :
- Google Cloud Storage.
- Github pages.

Once this is done installation step would be:

```
helm repo add agones our_repo_url
helm install agones/agones
```

**Comment by markmandel** [comment]
Ooh! I love this idea - I need to read up on this, but maybe this will also make installing dev versions of Agones easier as well.

We have the domain agones.dev - we can likely do a charts.agones.dev or something similar.

**Comment by Kuqd** [comment]
I ‘m thinking to add a google cloud storage bucket ´agones-charts’ with a backend (load balancer) to redirect https://agones.dev/helm.

Then we add all previous releases to the bucket. We also add a step to push a release( helm package + gcs copy) in the release make target.

Finally we should update the release and installation process documentation, the later should be 

´´´
helm repo add agones https://agones.dev/helm
helm install agones/agones 
´´´

That should install the latest version (user can also see the list of version using ´helm repo list’)

Question: does agones/agones feels right ?

**Comment by markmandel** [comment]
I wonder if we even need the load balancer. I already run an app-engine app at agones.dev - so we could just modify that to serve out of the GCS bucket.

Maybe through: https://github.com/google/weasel even?

**Comment by Kuqd** [comment]
This is ready to test see my branch:

https://github.com/Kuqd/agones/commit/af17eedcc16388ee78642b847f1aad0a7c1d06c1

I've added 3 targets (one to package the chart, one push and one to push a specific version).

Once this is tested I would update doc and do-release target.

**Comment by markmandel** [comment]
@Kuqd - Just to confirm - I need to create a redirect from agones.dev/chart/stable to https://storage.googleapis.com/agones-chart/ ?

**Comment by Kuqd** [comment]
yes please !

**Comment by markmandel** [comment]
@Kuqd I've setup a redirect from http://agones.dev/chart/stable to https://storage.googleapis.com/agones-chart/

I don't know if I'll need to redirect certain file requests, I've just done the singular path. Let me know how testing goes.

**Comment by Kuqd** [comment]
everything under the bucket should be curlable such as
```
curl https://agones.dev/chart/stable/index.yaml
curl https://agones.dev/chart/stable/agones-0.2.0.tgz
```

**Comment by markmandel** [comment]
Try now :smile:

**Comment by Kuqd** [comment]
We're all set: 

```
helm repo add agones https://agones.dev/chart/stable/          
"agones" has been added to your repositories
 helm search agones                                            
NAME            CHART VERSION   APP VERSION     DESCRIPTION
agones/agones   0.4.0           0.4.0           a library for hosting, running and scaling dedi...
```

**Comment by markmandel** [comment]
Awweessome. So what are next steps? Documentation?

**Comment by Kuqd** [comment]
I have updated the documentation but repo doesn't work anymore. I wanted to add info on how to install a specific release.

**Comment by markmandel** [comment]
Do I need to make any additional changes to make it so the repo works?

**Comment by Kuqd** [comment]
hum it works on my work station but not at home ... I will investigate
