### ISSUE TITLE
Document how to configure maximum number of pods/node that can be allocated

### ISSUE THREAD

**Issue by victor-prodan** [GoogleCloudPlatform/agones#295]
While operating dedicated game servers, CPU usage is not a good indicator of node load. The server  can mix idle periods (players loading, in lobby, etc) with burst periods (intense gameplay). 

You can thus put too many pods in a node because their servers are idle and then when gameplay starts they will starve one another leading to lag, player disconnections or even server crashes.

I propose to be able to configure a maximum amount of pods/node or even better - somehow tie this cap to the number of cpus of the node (if possible).

**Comment by Kuqd** [comment]
I think Kubernetes does this already for you. 

If within your pod spec template you provide a resource properties you can express the maximum and minimum CPU required see  https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

Now when you set this properly for you gameserver expectations, Kubernetes can (if activated) auto scale nodes based on pods requirements.

Would this works ?

**Comment by markmandel** [comment]
Or another angle - I wrote about doing this:
https://www.compoundtheory.com/scaling-dedicated-game-servers-with-kubernetes-part-2-managing-cpu-and-memory/

And this paragraph seems relevant:
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-requests-are-scheduled

If we are happy about this - this is something we should likely document/faq on our end, as it'll be a common question.

**Comment by victor-prodan** [comment]
Yes, it looks like what I wanted. Can you use this issue as a request to add doc/examples?

**Comment by markmandel** [comment]
SGTM. Marked as such, and changed the title. :+1: 

Now to work out where we want this to go. Maybe we need a FAQ?

**Comment by victor-prodan** [comment]
I would like a default setting added to the existing configuration examples, as scaling is an important issue for dedicated servers. Or at least a comment....

**Comment by markmandel** [comment]
I added
https://github.com/GoogleCloudPlatform/agones/blob/master/docs/limiting_resources.md

Recently. Does this cover this topic, or do we feel there is more that we can write here?

(Basically asking if we can close this ticket)

**Comment by markmandel** [comment]
Awesome. Closed! :man_cartwheeling:
