### ISSUE TITLE
When running the SDK sidecar in local mode, be able to specify the backing `GameServer` configuration

### ISSUE THREAD

**Issue by victor-prodan** [GoogleCloudPlatform/agones#296]
I am testing locally the game server with the sidecar launched independently in --local mode.
The thing is that in this case, the name of the port created by the sidecar ("default") does not match the name of the port from the yaml file used with a real deployment.
I would like to be able at least to change the "default" port name.

**Comment by Kuqd** [comment]
@victor-prodan are we talking about the grpc/http or gameserver port ?

**Comment by markmandel** [comment]
What about this idea: If you could optionally specify a `GameServer` yaml file that you could pass in, that would be the details that are passed back when you want the `GameServer` configuration.

Something like:

`sdk-server.linux.amd64 --local -f gameserver.yaml`

Would that work? Seems like the most flexible.

**Comment by victor-prodan** [comment]
I was talking about gameserver port and yes, specifying the gameserver.yaml would be perfect!
