### ISSUE TITLE
As game server, I want to set metadata that will be retrieved by matchmaker in the moment of allocation

### ISSUE THREAD

**Issue by victor-prodan** [GoogleCloudPlatform/agones#298]
This metadata can be set for example when server calls Ready()
Useful for example to pass some secret that the clients will need to be able to connect (to prevent cheating/hacking).
Can also be used to pass an url that accesses server remote access/monitoring, custom Ids, etc

**Comment by markmandel** [comment]
I believe this is coming - please have a look at the design [here](https://github.com/GoogleCloudPlatform/agones/issues/279#issuecomment-404947105)

Let me know if that will meet your needs, and if so, I'll mark this as duplicate.

**Comment by victor-prodan** [comment]
Yes, #2 seems to do what I asked for

**Comment by markmandel** [comment]
Awesome. marking as duplicate to #279 and closing.
