### ISSUE TITLE
Add unhealthy message to sdk

### ISSUE THREAD

**Issue by nikibobi** [GoogleCloudPlatform/agones#302]
Currently game servers send health checks every few seconds and if they stop they become unhealthy. I think an unhealthy method should be added for times when the game server knows it's in a bad state. It should be sent once and the server marked unhealthy.

**Comment by markmandel** [comment]
Interesting idea! Curious though - if you know you are unhealthy, why not call `Shutdown()` and self terminate?

At least at this stage, that will end up happening anyway. Or are you looking to use the Unhealthy state for something?

**Comment by nikibobi** [comment]
With unhealthy you know something has happened and maybe should investigate. I think shutdown should be used when a match is over and the game ended normally.

**Comment by markmandel** [comment]
That's a fair point - but that would mean `Unhealthy` would show up in the resource state, and the event list - which would only be persistent until the resource got deleted - so not that long? At which point, it's gone.

You may be better off just doing some of your own process logging before Shutting something down, and alerting/introspecting/analysing on the aggregated logs?

Curious - is there precedent for this anywhere else? (i.e. Gamelift, i3d, etc?).

I'm also thinking about visualisations etc - and if you mark it as Unhealthy, it could definitely show up there.

Also curious - what sort of situations would you see this happening in -- wherein you know the gameserver is no longer healthy?

**Comment by nikibobi** [comment]
I don't have a specific use case and I you are right that the resource will get deleted right after. Visualisations would be great.

**Comment by Kuqd** [comment]
@nikibobi Are we happy to close this one ? I also leaning toward metrics on logging to alert on gameserver failure as this will last longer than kubernetes state.

**Comment by nikibobi** [comment]
@Kuqd yes, you are right that a more persistent solution is better.
