### ISSUE TITLE
Update "Developing, Testing and Building Agones" tutorial with how to push updates to your test cluster

### ISSUE THREAD

**Issue by victor-prodan** [GoogleCloudPlatform/agones#308]
I followed the Developing, Testing and Building Agones instructions and they worked pretty well to push and test the first build to GKE.

The problem occurred when I had made some changes locally (to the agones controller) and I wanted to push my changes to the cluster. 

After multiple trial and error I discovered that it is possible by:
- push the new images to gcr.io (make push)
- delete the current agones install by using the generated install yaml file (make shell + kubectl delete ./install/yaml/install.yaml
- re-install agones: exit the shell and make install

I suggest adding this explanation to the tutorial and maybe also add a "make install-update" or "make reinstall" build target.

**Comment by markmandel** [comment]
You are correct - we should be clear about making changes.

That being said - it should be a repeat of the original process:

(for GKE, add the minikube prefix for minikube)
`make build-images`
`make push`
`make install`

Or you could do this in one go:
`make build-images push install`

(You may need to `gcloud-auth-docker` somewhere, but the general gist stays the same)

**Comment by victor-prodan** [comment]
The thing is that make install does not make K8s to pull the new image and update the controller. I think this might be because the new image has the same label and the default pull policy is 'if it does not exist'

**Comment by markmandel** [comment]
So `make install` on GKE _should_ set the `imagePullPolicy` to `Always`.

Where you using `make install` ? (basically, where you using the development tooling?)

**Comment by victor-prodan** [comment]
I'm using it in a CentOS 7 VirtualBox.
After running make install, I did a "get pods --namespace agones-system"
and noticed that the up time for the pod was unchanged.
As the image had the same label, there was no other way for me to check if
the controller was updated.

**Comment by markmandel** [comment]
:man_facepalming: of course. You would actually have to delete the pod, for the new one to be pulled down.

Yeah, this should be documented as well. Good catch.

**Comment by markmandel** [comment]
@Kuqd looking at #309 as well - should we add `--recreate-pods` to our Makefile `install` commands for development purposes. Would solve part of this this issue as well. WDYT?

**Comment by victor-prodan** [comment]
I think this is fixed now.
`make install` always recreates the pods and #349 added more doc.
