### ISSUE TITLE
As game server, I want to get the Agones sidecar version

### ISSUE THREAD

**Issue by victor-prodan** [GoogleCloudPlatform/agones#310]
Useful mainly for logging, to know with what version of Agones sidecar you're running.
But game servers could also require a minimum (or a specific) version to run.

Maybe add it as an annotation?

**Comment by markmandel** [comment]
The Agones sidecar does send its version to its own log stream, which will get added to the logs for the Pod, so it should be there already.

But I like the idea of adding the Agones version to a `GameServer` (and maybe all resources?) as an annotation. Could be useful as upgrades happen. :+1: I can see that being useful.

**Comment by markmandel** [comment]
@aLekSer , @victor-prodan I assume we can close this now, due to #498 ?
