### ISSUE TITLE
As developer, I want to emulate an allocation in local mode

### ISSUE THREAD

**Issue by victor-prodan** [GoogleCloudPlatform/agones#314]
This is useful to be able to work on the server integration locally.

**Comment by markmandel** [comment]
You can always setup minikube locally - that is an option.

That being said, I can definitely see use cases for just having the lightweight local sidecar.

Any thoughts on how this would work? Some kind of way to talk to the binary?

Maybe the binary watches the gameserver.yaml file that gets passed in #296 - and if it get's changed, it fires the change up through the SDK (when #277 callback works)? So you could set the Status values in there as required?

That idea doesn't seem too bad? WDYT?

**Comment by victor-prodan** [comment]
I see two solutions:
1. Pass a fleetallocation.yaml as parameter. In this case, the sidecar will automatically allocate the server as soon as it reports ready ( or maybe with a configurabile delay but that's not a must)
2. In localode, sidecar extends its REST api with extra options that can be used by dev itself. This would be useful for simulating other cluster events as well, but I cant think of an actual example right now

**Comment by markmandel** [comment]
Now we have #413 we can close this issue.

Any objections?

**Comment by markmandel** [comment]
Looks like no objections. Will close for now, let's reopen/have a new ticket if there is more functionality we may need.
