### ISSUE TITLE
Fleet allocation request could not find fleet

### ISSUE THREAD

**Issue by KamiShepard** [GoogleCloudPlatform/agones#324]
I am implementing fleet allocation in node through REST request to kubernetes api, and it doesn't seem to work. 

I POST to `/apis/stable.agones.dev/v1alpha1/namespaces/default/fleetallocations` with JSON body

```
{
  "apiVersion": "stable.agones.dev/v1alpha1",
  "kind": "FleetAllocation",
  "metadata": {
    "generateName": "simple-udp-"
  },
  "spec": {
    "fleetName": "simple-udp"
  }
}
```

And it returns error:
```
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "admission webhook \"validations.stable.agones.dev\" denied the request: Invalid FleetAllocation",
    "reason": "Invalid",
    "details": {
        "group": "stable.agones.dev",
        "kind": "FleetAllocation",
        "causes": [
            {
                "reason": "FieldValueNotFound",
                "message": "Cloud not find fleet simple-udp",
                "field": "fleetName"
            }
        ]
    },
    "code": 500
}
```

However if I do it through command line and post this:
`kubectl create -f https://raw.githubusercontent.com/GoogleCloudPlatform/agones/master/examples/simple-udp/fleetallocation.yaml -o yaml`

It works fine and returns new allocated instance. 
Am I doing something wrong? 

Just to confirm, if I do GET on `/apis/stable.agones.dev/v1alpha1/namespaces/default/fleets` there is defeinitely a fleet `"name": "simple-udp"`

**Comment by markmandel** [comment]
Looking into this, to see if I can replicate - Can you provide Kubernetes implementation details? Version, if it's hosted - which hosted version?

**Comment by KamiShepard** [comment]
Hosted on GKE using agones 0.3.0

`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd6
4"}`

`Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.4", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-08-04T03:47:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:
"linux/amd64"}`

**Comment by markmandel** [comment]
Worked it out - there's a bug in my code (or k8s, depending on how you look at it).
kubectl looks to populate the `metadata.namespace` with the default namespace whereas the API won't - because reasons.

I think I can work around this in my code, but for now, here's a workaround for you (and I'm going to document this as well):

```
curl -d '{"apiVersion":"stable.agones.dev/v1alpha1","kind":"FleetAllocation","metadata":{"generateName":"simple-udp-", "namespace": "default"},"spec":{"fleetName":"simple-udp"}}' -H "Content-Type: application/json" -X POST http://localhost:8001/apis/stable.agones.dev/v1alpha1/namespaces/default/fleetallocations
```

Good find!
