### ISSUE TITLE
Health messages logged with wrong severity

### ISSUE THREAD

**Issue by steven-supersolid** [GoogleCloudPlatform/agones#335]
Running in GKE and viewing logs in Stackdriver Logging, health message logs are still seen when the log filter level is set to Error. The level inside the message is "info" but severity is "ERROR"

E.g.
`2018-08-31 17:16:44.000 BST
{"msg":"Health Ping Received","level":"info","source":"*gameservers.SDKServer"}`
```
{
 insertId:  "7i33dlfktfmsv"  
 jsonPayload: {…}  
 labels: {…}  
 logName:  "projects/xxx/logs/agones-gameserver-sidecar"  
 receiveTimestamp:  "2018-08-31T16:16:46.466567315Z"  
 resource: {…}  
 severity:  "ERROR"  
 timestamp:  "2018-08-31T16:16:44Z"  
}
```

Not sure if this is a bug with Agones or a project configuration issue.

**Comment by markmandel** [comment]
I actually think all logs in gke come through as Error level (not sure why) - but will double check.
