### ISSUE TITLE
Agones sdk-server sidecar should have cpu and memory limits

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#344]
Right now the sdk-server sidecar will default to 0.1 cpu usage (not sure on memory).

This feels like overkill for the sidecar server, as it doesn't do very much, and is a waste of good cpu!

We should measure this, and set appropriate limits.

We should also make this helm configurable.

## Implementation
Add resource limits here:
https://github.com/GoogleCloudPlatform/agones/blob/master/pkg/gameservers/controller.go#L440

**Comment by KamiShepard** [comment]
Active server with 50 clients connected to the game server
![image](https://user-images.githubusercontent.com/2967343/47100933-9e3f1e80-d230-11e8-9142-67110ab6689a.png)

**Comment by KamiShepard** [comment]
Another sample with 50 clients connecting to the game server
![image](https://user-images.githubusercontent.com/2967343/47103002-22e06b80-d236-11e8-939e-8cc23db78ffc.png)

**Comment by markmandel** [comment]
@KamiShepard Did you (or anyone else for that matter) have any opinions on whether this should be a limit or a request?

https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

**Comment by KamiShepard** [comment]
Left game running all night with 50 active clients connected:
![image](https://user-images.githubusercontent.com/2967343/47148167-df364200-d2c7-11e8-976f-076149d6b4c7.png)
