### ISSUE TITLE
C++ SDK no destructor body

### ISSUE THREAD

**Issue by nikibobi** [GoogleCloudPlatform/agones#366]
For some time now I got weird linker errors when I try to `delete` pointer to `agones::SDK`. When I looked at the source I saw that there is a destructor declared in the `.h` file, but it is missing in the `.cpp` file.

There are a few ways to fix it:

1. Delete the declaration in the header file: ~~`~SDK();`~~
2. Add empty body in cpp file: `agones::SDK::~SDK() { }`
3. Set it equal to default in the header file: `~SDK() = default;`

**Comment by markmandel** [comment]
Please submit a PR! My c++ is not good, as you can see!
