### ISSUE TITLE
Fleet Auto Scaler watch

### ISSUE THREAD

**Issue by santhh** [GoogleCloudPlatform/agones#382]
Hello everyone: How does watch work for fleet auto scaler?  I am trying to watch this but it does not send any stream.

http://localhost:8001/apis/stable.agones.dev/v1alpha1/namespaces/default/fleetautoscalers&watch=true
Is this normal? I am trying to get  stats in stackdriver about how many GS read vs allocated in real time

**Comment by markmandel** [comment]
If you want to manually watch an API - you should follow these guidelines:
https://kubernetes.io/docs/reference/using-api/api-concepts/

But I would recommend using one of the clients to do this - the go generated client in this library would likely work best, but there is CRD support for other languages of varying capabilities.

**Comment by markmandel** [comment]
Closing this, as it looks like the question is answered.
