### ISSUE TITLE
Missing or incomplete allocation event and "really ready" state

### ISSUE THREAD

**Issue by think01** [GoogleCloudPlatform/agones#404]
We're working on integration between Unreal Engine and Agones.
Our use case is a simple match making scenario, where users can choose some details about the newly created lobby. So the game server needs some time not only to load the map (which it executes before calling sdk.ready()) but to customize it, modifying the scene and maybe loading some other assets, before actually being able to accept player connections.

These details are passed from the game manager to the game server via custom annotations on the FleetAllocation creation.

First question is: how the game server can know when it is being allocated? Is it possible only through sdk.watch()?
Second question: how can we guarantee that the game server is actually ("really") ready to accept connections? It needs some additional time to prepare the map with the required details from the allocation. For what we've seen so far, there's no direct support for this phase by Agones, am I correct?

Thanks in advance for any hint/feedback.

Best Regards,
Fabio Da Soghe

**Comment by markmandel** [comment]
> how the game server can know when it is being allocated? Is it possible only through sdk.watch()?
Yes exactly - that's one of the uses for sdk.watch! Keep an eye out for the state changing to 'Allocated' and react accordingly.

> how can we guarantee that the game server is actually ("really") ready to accept connections?
We recommend setting a label/annotation through the SDK, that can be viewed/watched externally through the Kubernetes API. This lets you set whatever states are relevant for your game, without having to build a "one solution fits all".

Does that answer your question?

**Comment by markmandel** [comment]
Thanks for taking the time to write out your thoughts - to provide some context, here is the previous design discussion, that also covers many of these topics:
https://github.com/GoogleCloudPlatform/agones/issues/279

The TL;DR of your suggestion of blocking on allocation until loading (or other operations) was that the backing tech has a hard 30s timeout that we can't change (at least at this stage), and the consequences of it failing could cause really bad things to happen to GameServers.

If we can work out these issues, I'm definitely not against this idea (there are some other concurrency and performance considerations - it's not 100% simple, but they are solvable), but we've yet to determine a design that works.

Maybe there is a way we can make it easier to wait/watch for specific labels/annotations on a GameServer - and come at it a different way.

**Comment by markmandel** [comment]
It may be worth noting (and this may be something we need to document better -- I was thinking about this, this morning). You can watch a specific `GameServer` for changes through the K8s API without (i think), too much difficulty:

For example, watching for changes on a `GameServer` named `simple-udp`:

```
root@d7983a0bc99a:/go/src/agones.dev/agones# curl http://localhost:8001/apis/stable.agones.dev/v1alpha1/watch/namespaces/default/gameservers/simple-udp
{"type":"ADDED","object":{"apiVersion":"stable.agones.dev/v1alpha1","kind":"GameServer","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"stable.agones.dev/v1alpha1\",\"kind\":\"GameServer\",\"metadata\":{\"annotations\":{},\"name\":\"simple-udp\",\"namespace\":\"default\"},\"spec\":{\"ports\":[{\"containerPort\":7654,\"name\":\"default\",\"portPolicy\":\"dynamic\"}],\"template\":{\"spec\":{\"containers\":[{\"image\":\"gcr.io/agones-images/udp-server:0.4\",\"name\":\"simple-udp\"}]}}}}\n"},"clusterName":"","creationTimestamp":"2018-11-06T00:35:55Z","finalizers":["stable.agones.dev"],"generation":1,"name":"simple-udp","namespace":"default","resourceVersion":"3353705","selfLink":"/apis/stable.agones.dev/v1alpha1/namespaces/default/gameservers/simple-udp","uid":"ec13784a-e15b-11e8-948e-42010a8a00e6"},"spec":{"container":"simple-udp","health":{"failureThreshold":3,"initialDelaySeconds":5,"periodSeconds":5},"ports":[{"containerPort":7654,"hostPort":7755,"name":"default","portPolicy":"dynamic","protocol":"UDP"}],"scheduling":"Packed","template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"image":"gcr.io/agones-images/udp-server:0.4","name":"simple-udp","resources":{}}]}}},"status":{"address":"35.203.182.203","nodeName":"gke-test-cluster-default-2f036472-9wrr","ports":[{"name":"default","port":7755}],"state":"Ready"}}}
```

**Comment by think01** [comment]
I didn't see that issue, indeed it's very on topic. The 30 seconds timeout is a real problem here, I understand the design choices taken.

Thank you again for this explanation, much instructive.

Keep up the good work!
Fabio

**Comment by markmandel** [comment]
Are you happy with me closing this issue?

**Comment by markmandel** [comment]
> and I've implemented the watch method, it works like a charme ^_^ 
:point_up:  awesome!

Closing!

As an aside - if you feel there are some places our docs could be better to talk about this - maybe an enhancement to a guide or whatever, PRs are definitely welcome!

**Comment by think01** [comment]
> As an aside - if you feel there are some places our docs could be better to talk about this - maybe an enhancement to a guide or whatever, PRs are definitely welcome!

I'll think about it, good idea.
