### ISSUE TITLE
Add Agones to helm hub

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#450]
We should have a entry in
https://hub.helm.sh/

(I would probably advocate after 0.7.0,  just because of the CRD fix)

**Comment by Kuqd** [comment]
Process can be found here : https://github.com/helm/hub/blob/master/Repositories.md

**Comment by Kuqd** [comment]
done here https://github.com/helm/hub/pull/32

We should make sure our logo is on the chart.

**Comment by Kuqd** [comment]
Merged
