### ISSUE TITLE
Race condition in SDK.SetLabel and SDK.SetAnnotation

### ISSUE THREAD

**Issue by jkowalski** [GoogleCloudPlatform/agones#455]
I believe there's currently a race condition in SDK.SetLabel and SDK.SetAnnotation implementation which causes the labels to sometimes go back in time, because when SDK server performs read-modify-write on GameServer object, it does not read the fresh state of GameServer, but a cached one, thus it may overwrite labels/annotations back to old values.

Example: assuming game server sets the labels like that:

```
SDK.SetLabel(A,1)
SDK.SetLabel(B,1)
SDK.SetLabel(A,2)
SDK.SetLabel(B,2)
```

every observer (using GET/LIST) should always see value of A>=B because A increase happens before B increase.

Now imagine there's a propagation delay after `SetLabels(A,2)`. When `SetLabel(B,2)` executes, the cached GS still contains `{A=1,B=1}`, and SDK server will set labels: `{A=1,B=2}` which violates the invariant.

This is quite easy to reproduce in E2E test, even with very little load in the cluster.

**Comment by jkowalski** [comment]
(BTW. I have a failing test and can work on a fix, can sb assign this to me?)

**Comment by markmandel** [comment]
Does setting the labels not increase the generation - and thereby force a retry if the data has been changed?

**Comment by jkowalski** [comment]
I don't think there's any mechanism to force a retry automatically that would work here. In this case the problem is because we're relying on stale data and trusting it as fresh.

BTW. One possible fix is to use Getter (always fresh, strongly consistent) instead of Lister (eventually consistent).

Perhaps an even better fix is to support coalescing multiple labels/annotations into a single read-modify-write against GS - this would be a good way of supporting retries and implementing #310 without excessive API server traffic.

**Comment by markmandel** [comment]
Both SetLabel and SetAnnotation operations specifically go into a workerqueue, so they do retry of they fail. Or at least, they should!

**Comment by jkowalski** [comment]
There is no failure anywhere here - all API server calls succeed. It's just a propagation delay.

**Comment by Yingxin-Jiang** [comment]
I am working on the issue.

**Comment by Yingxin-Jiang** [comment]
In my local test, I updated TestSDKSetLabel to set multiple labels on the game server, https://github.com/GoogleCloudPlatform/agones/blob/dcb7dfaf11266e5d39b6aaee297eb1a77603716b/test/e2e/gameserver_test.go#L56

I couldn't reproduce what jkowalski described. 

I did see some SetLabel operations failed. Then they were added back into the workerqueue and retried. This confirms markmandel's comment, https://github.com/GoogleCloudPlatform/agones/issues/455#issuecomment-449531271

> Both SetLabel and SetAnnotation operations specifically go into a workerqueue, so they do retry of they fail. Or at least, they should!

**Comment by jkowalski** [comment]
The repro is here:

https://github.com/jkowalski/agones/commit/717e242916823d161507efdd8085bcc5248025b7

(you need to use latest udp-server:0.6, just sync to latest code).

The test creates 2 labels "foo" and "bar" going from from 'val-001' .. 'val-100' and an observer which gets the game server and looks at labels evey 100ms.

```
2019/02/06 17:33:19 got foo  (previous ) bar  (previous )
2019/02/06 17:33:19 got foo val-001 (previous ) bar val-001 (previous )
2019/02/06 17:33:19 got foo val-002 (previous val-001) bar val-001 (previous val-001)
2019/02/06 17:33:20 got foo val-003 (previous val-002) bar val-002 (previous val-001)
2019/02/06 17:33:20 got foo val-004 (previous val-003) bar val-003 (previous val-002)
2019/02/06 17:33:20 got foo val-005 (previous val-004) bar val-004 (previous val-003)
2019/02/06 17:33:20 got foo val-006 (previous val-005) bar val-005 (previous val-004)
2019/02/06 17:33:20 got foo val-006 (previous val-006) bar val-006 (previous val-005)
2019/02/06 17:33:20 got foo val-007 (previous val-006) bar val-006 (previous val-006)
2019/02/06 17:33:20 got foo val-007 (previous val-007) bar val-007 (previous val-006)
2019/02/06 17:33:21 got foo val-008 (previous val-007) bar val-008 (previous val-007)
2019/02/06 17:33:21 got foo val-009 (previous val-008) bar val-008 (previous val-008)
2019/02/06 17:33:21 got foo val-009 (previous val-009) bar val-009 (previous val-008)
2019/02/06 17:33:21 got foo val-010 (previous val-009) bar val-009 (previous val-009)
2019/02/06 17:33:21 got foo val-010 (previous val-010) bar val-010 (previous val-009)
2019/02/06 17:33:21 got foo val-010 (previous val-010) bar val-010 (previous val-010)
2019/02/06 17:33:21 got foo val-011 (previous val-010) bar val-010 (previous val-010)
2019/02/06 17:33:21 got foo val-011 (previous val-011) bar val-010 (previous val-010)
2019/02/06 17:33:22 got foo val-011 (previous val-011) bar val-011 (previous val-010)
2019/02/06 17:33:22 got foo val-012 (previous val-011) bar val-011 (previous val-011)
2019/02/06 17:33:22 got foo val-012 (previous val-012) bar val-011 (previous val-011)
2019/02/06 17:33:22 got foo val-012 (previous val-012) bar val-012 (previous val-011)
2019/02/06 17:33:22 got foo val-012 (previous val-012) bar val-012 (previous val-012)
2019/02/06 17:33:22 got foo val-012 (previous val-012) bar val-013 (previous val-012)
2019/02/06 17:33:22 got foo val-012 (previous val-012) bar val-013 (previous val-013)
2019/02/06 17:33:23 got foo val-012 (previous val-012) bar val-013 (previous val-013)
2019/02/06 17:33:23 got foo val-012 (previous val-012) bar val-014 (previous val-013)
2019/02/06 17:33:23 got foo val-012 (previous val-012) bar val-014 (previous val-014)
2019/02/06 17:33:23 got foo val-015 (previous val-012) bar val-014 (previous val-014)
2019/02/06 17:33:23 got foo val-015 (previous val-015) bar val-015 (previous val-014)
2019/02/06 17:33:23 got foo val-016 (previous val-015) bar val-015 (previous val-015)
2019/02/06 17:33:24 got foo val-016 (previous val-016) bar val-015 (previous val-015)
2019/02/06 17:33:24 got foo val-013 (previous val-016) bar val-015 (previous val-015)
--- FAIL: TestSDKSetLabelRace (9.13s)
    gameserver_test.go:127: foo went back in time val-013, was val-016
FAIL
```

**Comment by jkowalski** [comment]
I think the root cause is different than what I originally speculated, it's the fact that when we re-queue a work item after update failure it is scheduled to run in the future, after subsequent requests for the same key.

In this case looks like we lost an update race when trying to set "foo=val-013" so it was rescheduled and ran after "val-016"

**Comment by Yingxin-Jiang** [comment]
@jkowalski - Yes, your latest comment matched what I saw in my local test.

**Comment by Yingxin-Jiang** [comment]
Sent out pull request to fix the issue of lost on update race, https://github.com/GoogleCloudPlatform/agones/pull/584
