### ISSUE TITLE
Improve fleet scaling performance

### ISSUE THREAD

**Issue by jkowalski** [GoogleCloudPlatform/agones#483]
Currently when spinning up a large test fleet (10K GameServers) the Game Servers and pods are created relatively slowly (about 1 per second, measured on regional GKE cluster with 150 nodes * (8 cores + 8 GB RAM each)).

I think we're unnecessarily serializing something - in principle there should be no reason why this would be significantly slower than a deployment (which creates all pods almost instantaneously and they run in parallel).

**Comment by markmandel** [comment]
@jkowalski can we close this ticket now? I feel like we have acceptable performance at this stage?

**Comment by markmandel** [comment]
Going to close this ticket, as I think we've reached out goals here for now.

Please feel free to reopen if we need to.
