### ISSUE TITLE
FleetAllocation creation error lacks of information

### ISSUE THREAD

**Issue by Kuqd** [GoogleCloudPlatform/agones#485]
If your current fleet is full and you try to allocate a new GameServer via FleetAllocation as such

```golang
fa, err := client.Agones().StableV1alpha1().FleetAllocations("").Create(&newfa)
```

the error contains

```golang
&k8serrors.StatusError{
    ErrStatus: v1.Status{
        Code:    500,
        Reason:  v1.StatusReasonInternalError,
        Status:  v1.StatusFailure,
        Message: "Internal error occurred: admission webhook \"mutations.stable.agones.dev\" denied the request: NotFound ",
    },
}
```

I think we should improve this so that we can handle gracefully this kind of error currently the only way to differentiate from `InternalServerError` is to use a function like this

```golang
func isUnallocatable(err error) bool {
	switch t := err.(type) {
	case k8serrors.APIStatus:
		return t.Status().Reason == v1.StatusReasonInternalError && t.Status().Status == v1.StatusFailure &&
			strings.Contains(t.Status().Message, "admission webhook \"mutations.stable.agones.dev\" denied the request: NotFound")
	}
	return false
}
```

This is may be obsolete as FleetAllocation will deprecated ?

**Comment by markmandel** [comment]
Yes - this exact problem is solved by `GameServerAllocation` - in that it only returns an error if something goes horribly wrong.

If an allocation fails, it returns with a status of `UnAllocated` for exactly this scenario.

**Comment by Kuqd** [comment]
Ok let’s close this then
