### ISSUE TITLE
If you modify the `Scheduling` on a Fleet, it does not flow down to the `GameServerSet`.

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#495]
Bug is pretty much as described.

The logic should probably be, if you change the Fleet, it should update the GameServerSet.

But don't go update all the GameServers this is too much work, let's wait until it flows out to the rest of the `GameServers` as they shutdown and restart.

**Comment by pooneh-m** [comment]
I'm working on this.

**Comment by markmandel** [comment]
Closing now that #582 is done.
