### ISSUE TITLE
Remove all the kubectl custom commands from the quickstarts

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#521]
Since we are now on Kubernetes 1.11, and we have better `kubectl` integration, we no longer need to do:

```
kubectl get gs -o=custom-columns=NAME:.metadata.name,STATUS:.status.state,IP:.status.address,PORT:.status.ports
```

And all versions that have `custom-columns`. We should remove these from the quickstart docs, and replace with `kubectl get gs`, and also match up the output with our now current output.

**Comment by hpandeycodeit** [comment]
@markmandel I can work on this.

**Comment by markmandel** [comment]
Just realised we can close this.  This is done!
