### ISSUE TITLE
Approver access for @jkowalski

### ISSUE THREAD

**Issue by jkowalski** [GoogleCloudPlatform/agones#526]
### GitHub Username
@jkowalski

### Requirements
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have read the [contributor guide](../../CONTRIBUTING.md)
- [x] I am actively contributing to Agones
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @markmandel
- @kuqd

### List of contributions to the Agones project

- PRs reviewed / authored

(sample, total 16 so far)

#451 - Split pkg/gameservers into two
#475 - added game server state diagram
#497 - made QPS, burst QPS and number of workers externally configurable
#500 - improved isolation of Agones controllers using taints and priority
#501 - Prometheus and grafana improvements based on load testing experience
#512 - run cleanup before tests in addition to after

- Issues responded to

#489 - Assign higher priority to Agones system pods
#453 - Improve build speed by refactoring Makefile
#445 - Move SDK server code from pkg/gameservers to a separate package
#499 - Investigate why increasing worker count/QPS causes E2E tests to fail
#483 - Improve fleet scaling performance
#484 - Fleet scheduling: Packed not working correctly

**Comment by markmandel** [comment]
:+1: 

@Kuqd you good? :smile:

**Comment by Kuqd** [comment]
I am

**Comment by markmandel** [comment]
Making @jkowalski an approver right now...

**Comment by markmandel** [comment]
And done. Congratulations to @jkowalski for becoming our newest approver!

![Excellent!](https://media.giphy.com/media/l46CDHTqbmnGZyxKo/giphy.gif)
