### ISSUE TITLE
Create Node.js library

### ISSUE THREAD

**Issue by steven-supersolid** [GoogleCloudPlatform/agones#538]
We are currently using the REST API which works well but it may simplify things for new users to have a library to use with Node.js. When deploying a new Agones version with an API change, a developer would only have to update their library version. Ideally this would be published as a node module as this is idiomatic for Node.js.

There has been some discussion before about creating a gRPC client in Node.js, or the library could make REST calls directly. The gRPC route should result in generated code so would be more maintainable.

**Comment by Kuqd** [comment]
for reference https://grpc.io/docs/tutorials/basic/node.html

**Comment by markmandel** [comment]
Here are the docs on how to statically generate a grpc client in node:
https://github.com/grpc/grpc/tree/v1.18.0/examples/node/static_codegen

**Comment by steven-supersolid** [comment]
Nice. This may be something I can do and manually test with our current setup. I can look at porting the client tests too. Unless there is any existing work done on this?

**Comment by markmandel** [comment]
Not that i'm aware of!

**Comment by steven-supersolid** [comment]
I started work on this and have created a project structure and generated the js files from .proto. Hope to spend more time on it this weekend
