### ISSUE TITLE
Labels referencing resources name can be too long

### ISSUE THREAD

**Issue by Kuqd** [GoogleCloudPlatform/agones#541]
In Kubernetes you can create a resource with a 253 characters long name :

> By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions.

However labels and annotations values are restricted to 63 characters :

> Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.

In Agones we're setting labels value for referencing parent resources, but if a parent resource has a long name this cause errors.

References:
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

/cc @victor-prodan

**Comment by aLekSer** [comment]
This give an error here:
```
 "agones.dev/agones/pkg/fleets.(*Controller).upsertGameServerSet
	/go/src/agones.dev/agones/pkg/fleets/controller.go:258"
```
I am thinking of CreationValidationHandler on Create and Update the Fleet to check the Fleet Name length (and insist on no more than 63).

**Comment by markmandel** [comment]
Can this now be closed, or do we need to do GameServer as well?

**Comment by aLekSer** [comment]
Let me check other places were we use name in labels.

**Comment by aLekSer** [comment]
@Kuqd I think this ticket could be closed now. All names which reside in Label covered with validation functions.
