### ISSUE TITLE
Gameserver's that are not assigned to a node are left behind even after the scale was lowered

### ISSUE THREAD

**Issue by ilkercelikyilmaz** [GoogleCloudPlatform/agones#543]
Autosclaing on the Kubernetes cluster was turned off.

- kubectl create -f ./fleet.yaml
- kubectl get fleet
NAME            SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
fleet-example   Packed       2         2         0           2       15s
- kubectl get pods
NAME                              READY   STATUS    RESTARTS   AGE
fleet-example-7x6k4-bn49h-wqbgl   2/2     Running   0          19s
fleet-example-7x6k4-vkpgv-98nc9   2/2     Running   0          19s
- kubectl get po -o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name | cut -f 1 -d " " | sort | uniq -c | sort
      1 NODE
      2 gke-my-cluster-1-default-c8dd396a-4fsl

- kubectl edit fleet fleet-example (Set the replicas to 600)
- Gameservers created but 493 were not assigned to a node 
-kubectl get po -o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name | cut -f 1 -d " " | sort | uniq -c | sort
      1 NODE
     26 gke-my-cluster-1-default-c8dd396a-6s57
     26 gke-my-cluster-1-default-c8dd396a-fgbk
     27 gke-my-cluster-1-default-c8dd396a-5zvq
     28 gke-my-cluster-1-default-c8dd396a-4fsl
    **493 <none>**
- then changed the replica size to 50 but the number of gameservers didn't go down:
- kubectl get fleet
NAME              SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
fleet-example   Packed                    50              600                          0           107     3h

**Comment by markmandel** [comment]
This feels very similar to #540 - or maybe even duplicate.

**Comment by ilkercelikyilmaz** [comment]
I was talking to Jarek and he thinks that both problems might have surfaced from same activity/situation, each issue captures different problem. We probably should keep this open.

**Comment by ilkercelikyilmaz** [comment]
Recent performance improvements and bug fixes seems to fix this issue. I can't repro anymore.
