### ISSUE TITLE
Grafana: add basic API Server graphs

### ISSUE THREAD

**Issue by jkowalski** [GoogleCloudPlatform/agones#546]
QPS per resource type/verb:

`sum(rate(apiserver_request_count[5m])) by (resource,verb)`

Latency percentiles for key resource types:

`apiserver_request_latencies_summary{resource=~"gameservers|fleets|pods",verb!~"WATCH|LIST",quantile="0.5"}`

Error rates:

`sum(rate(apiserver_request_count{code!~"2.."}[5m])) by (code)`

Perhaps with a nice drop-down to allow narrowing it down by "resource" for common resource types (fleets, gameservers, pods, etc.)

**Comment by jkowalski** [comment]
Perhaps also have a dedicated graph to update conflict rate (HTTP 409):

`sum(rate(apiserver_request_count{code="409"}[5m])) by (code,resource)`

**Comment by Kuqd** [comment]
There is already an API server graph do you want to improve it ?

**Comment by jkowalski** [comment]
We have a client view, this issue is about adding server-side view.

**Comment by aLekSer** [comment]
Hello @jkowalski , I can start adding these metrics.
