### ISSUE TITLE
Help us pick a new project logo! 

### ISSUE THREAD

**Issue by thisisnotapril** [GoogleCloudPlatform/agones#577]
Hi all! We're thinking about getting a new logo for Agones, and we want your thoughts! The project founders have selected three options. We want you to vote and tell us which one you prefer! 

Here's the options:

**Option 1:**
<p align="center">
<img width="463" alt="screen shot 2019-02-08 at 5 37 42 pm" src="https://user-images.githubusercontent.com/8482383/52514623-50c43400-2bc8-11e9-83ee-db097e59a6ca.png">
</p>

**Option 2:** 
<p align="center">
<img width="534" alt="screen shot 2019-02-08 at 5 37 33 pm" src="https://user-images.githubusercontent.com/8482383/52514624-50c43400-2bc8-11e9-8dda-1e7c0025d4a1.png">
</p>

**Option 3:**
<p align="center">
<img width="425" alt="screen shot 2019-02-06 at 4 52 30 pm" src="https://user-images.githubusercontent.com/8482383/52513759-beb92d00-2bc1-11e9-99a1-97af52412aed.png">
</p>

Got a favorite? Now, how to vote! We're going to do this cheesy emoji style. 

- For option 1, react to this post with the :+1:

- For option 2, react to this post with the :heart:

- For option 3, react to this post with the :tada:

Voting will close on Feb 12!

**Comment by nikkisingh0204** [comment]
looking more attractive than the other two

**Comment by pooneh-m** [comment]
How about adding a little Kubernetes icon on the light blue controller of the first option to show that it is a controller for Kubernetes?

**Comment by thisisnotapril** [comment]
> How about adding a little Kubernetes icon on the light blue controller of the first option to show that it is a controller for Kubernetes?

@markmandel @Kuqd what do you think of this idea?

**Comment by markmandel** [comment]
Honestly - nobody else does sub logos, so I'm personally not a fan. Better to be clean about it, and just have our own image.

That all being said - looks like we have a clear winner :+1:

**Comment by thisisnotapril** [comment]
Yep, sounds good! Now to design a t-shirt.... :)

**Comment by markmandel** [comment]
Since we've past the 12th, should we close this ticket? Winner winner is:

<p align="center">
<img width="463" alt="screen shot 2019-02-08 at 5 37 42 pm" src="https://user-images.githubusercontent.com/8482383/52514623-50c43400-2bc8-11e9-83ee-db097e59a6ca.png">
</p>

:fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks:
