### ISSUE TITLE
GKE scopes in installation and testing are overkill

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#614]
[GKE scopes](https://cloud.google.com/sdk/gcloud/reference/container/clusters/create) could be dropped to the new(?) `gke-default` scope, which is far less than what we have in either the [documentation](https://github.com/GoogleCloudPlatform/agones/blob/master/site/content/en/docs/Installation/_index.md#creating-the-cluster), our [e2e cluster](https://github.com/GoogleCloudPlatform/agones/blob/master/build/gke-test-cluster/cluster-e2e.yml) or [development test clusters](https://github.com/GoogleCloudPlatform/agones/blob/master/build/gke-test-cluster/cluster.yml.jinja).

Likely only needs someone to test creating a cluster with the default scope, and making the changes in those three places.

**Comment by aLekSer** [comment]
Started working on that issue

**Comment by aLekSer** [comment]
Currently if omitting the oauthScopes in [development test clusters](https://github.com/GoogleCloudPlatform/agones/blob/master/build/gke-test-cluster/cluster.yml.jinja). An error occurs `Cannot pull image agones-controller from the registry.`
And unauthorized error if executing `docker run ` on one of cluster nodes.
Will check other places where we could use `gke-default` scope.

**Comment by markmandel** [comment]
@aLekSer does this mean the alias's don't work via the deployment manager, just through gcloud?

**Comment by aLekSer** [comment]
@markmandel I was not able to find out this yesterday. Will let you know. In Jinja template it seems that only `https://www.googleapis.com/auth/compute` style oauthScopes are accepted. If I pass `gke-defaults`.
Tested that I could pass it this way:
```
gcloud container clusters create [CLUSTER_NAME] --cluster-version=1.11 \
  --no-enable-legacy-authorization \
  --tags=game-server \
  --enable-basic-auth \
  --password=supersecretpassword \
  --scopes=gke-default \
  --num-nodes=3 \
  --machine-type=n1-standard-1
``` 
 And after use install.yaml, cluster is working fine.
