### ISSUE TITLE
Data replication in case of gameserver container crashed

### ISSUE THREAD

**Issue by itthought** [GoogleCloudPlatform/agones#622]
Hi,

I have a scenario where multiple player joined a room (GameServer) and during playing game server get crashed. Is there any way to migrate their old game state of all user to new container(GameServer).

**Comment by markmandel** [comment]
Unfortunately, there is no in built memory replication facilities in Agones, or Kubernetes as a whole.

There is an ongoing issue re: [Pod migration](https://github.com/kubernetes/kubernetes/issues/3949), but it's a pretty complicated issue with a variety of edge cases.

**Comment by markmandel** [comment]
Going to close this, since I think this answers the question. Please re-open if you have follow up :+1:
