### ISSUE TITLE
QUIC Support

### ISSUE THREAD

**Issue by johnsoncodehk** [GoogleCloudPlatform/agones#635]
Agones currently supports both TCP and UDP protocols.
TCP latency is relatively high, while UDP is not reliable.
Is there any plan to support a reliable UDP protocol such as QUIC?

**Comment by markmandel** [comment]
QUIC is just UDP, and as such, is already supported.

Agones doesn't care what underlying serialisation or communication system you use, as long as it's TCP or UDP (is there anything else 😁?)

**Comment by alexandrem** [comment]
There is SCTP which Kubernetes supports as a feature gate since 1.12!

**Comment by markmandel** [comment]
Today I learnt what SCTP is! 👍

**Comment by johnsoncodehk** [comment]
After some digging, I learned that I need to use the QUIC package on the server and client.
I will try to use SCTP, thank you for mentioning it.
