### ISSUE TITLE
Feature shortcode does not behave correctly for versions > "0.10.0" (2 digit minor version)

### ISSUE THREAD

**Issue by aLekSer** [GoogleCloudPlatform/agones#650]
Steps to reproduce:
Set `expiryVersion` to `0.10.0` and `base_version` to 0.9.0 in one of md files.
Run `make site-server`. 
We will not see the doc part inside the shortcode:
```
{{% feature expiryVersion="0.10.0" %}}
{{% /feature %}}
```

While `{{% feature expiryVersion="0.9.1" %}}` works as expected.
The reason seems to be lexicographic comparison between strings, we should split the version into parts and compare them separately.

**Comment by markmandel** [comment]
Oh! That's a nice find. And frustrating! We should fix this :cry:

**Comment by aLekSer** [comment]
I will fix this shortcode tomorrow.
