### ISSUE TITLE
gcloud-auth-cluster: Create unique name for cluster role binding

### ISSUE THREAD

**Issue by markmandel** [GoogleCloudPlatform/agones#662]
In theory, the cluster role binding name that we hard code could already exist (maybe someone else set up the cluster by hand).

I think it would be nice to take a short hash of the user's account name (or any other relatively unique identifier), and incorporate that into the name of the cluster role binding in `gcloud-auth-cluster`

**Comment by aLekSer** [comment]
I am thinking of something cross-platform like this hash:
```
accountHash := $(shell echo - n $$(gcloud config get-value account) | openssl md5)
```
