### ISSUE TITLE
Agones e2e tests are flakey

### ISSUE THREAD

**Issue by pooneh-m** [GoogleCloudPlatform/agones#700]
TestFleetRecreateGameServerOnPodDeletion end to end test fails randomly after being added at https://github.com/GoogleCloudPlatform/agones/pull/684 with timeout errors: https://pantheon.corp.google.com/cloud-build/builds/86f515ce-c846-43a0-9715-7a71d3c18978?project=agones-images

--- FAIL: TestFleetRecreateGameServerOnPodDeletion (76.71s)
fleet_test.go:844: 
Error Trace:	fleet_test.go:844
Error: Received unexpected error:
timed out waiting for the condition

**Comment by markmandel** [comment]
This is fixed in #694 (mentioned this in Slack). Waiting on review.

**Comment by markmandel** [comment]
This should now be fixed!
