### ISSUE TITLE
Failed calling admission webhook

### ISSUE THREAD

**Issue by bramdutch0** [GoogleCloudPlatform/agones#707]
I was going through the Quickstart: Create a Game Server tutorial and am getting an error when I run "kubectl create -f https://raw.githubusercontent.com/GoogleCloudPlatform/agones/release-0.9.0/examples/simple-udp/gameserver.yaml".

The error I'm getting is:
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/GoogleCloudPlatform/agones/release-0.9.0/examples/simple-udp/gameserver.yaml": Internal error occurred: failed calling admission webhook "mutations.stable.agones.dev": Post https://agones-controller-service.agones-system.svc:443/mutate?timeout=30s: no endpoints available for service "agones-controller-service"

Haven't been able to find anything about this error in the documentation

**Comment by markmandel** [comment]
Thanks for submitting this issue. We're going to need some more information please:

 - What version of Kubernetes are you running?
 - What cloud provider are you running Kubernetes on?
 - What version of Agones are you running?
 - How did you install Agones?
 - Is there anything in the Agones controller logs? - https://agones.dev/site/docs/guides/troubleshooting/

**Comment by bramdutch0** [comment]
Thanks for the reply! 

**Version**
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.9-dispatcher", GitCommit:"e3f5193e8f1091a162af7e17a781e6a3129bcfd0", GitTreeState:"clean", BuildDate:"2019-03-28T18:13:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

**Cloud Provider**
Google cloud

**Agones Version**
release-0.9.0

Installed with the Yaml file

**Controller logs**
{"filename":"/home/agones/logs/agones-controller-20190416_181112.log","message":"logging to file","numbackups":99,"severity":"info","source":"main","time":"2019-04-16T18:11:12.768866791Z"}
{"ctlConf":{"MinPort":7000,"MaxPort":8000,"SidecarImage":"gcr.io/agones-images/agones-sdk:0.9.0","SidecarCPURequest":"30m","SidecarCPULimit":"0","SdkServiceAccount":"agones-sdk","AlwaysPullSidecar":false,"PrometheusMetrics":true,"Stackdriver":false,"KeyFile":"/home/agones/certs/server.key","CertFile":"/home/agones/certs/server.crt","KubeConfig":"","GCPProjectID":"","NumWorkers":100,"APIServerSustainedQPS":400,"APIServerBurstQPS":500,"LogDir":"/home/agones/logs","LogSizeLimitMB":10000},"message":"starting gameServer operator...","severity":"info","source":"main","time":"2019-04-16T18:11:12.768946255Z","version":"0.9.0"}
st *v1alpha1.GameServer: gameservers.stable.agones.dev is forbidden: User \"system:serviceaccount:agones-system:agones-controller\" cannot list gameservers.stable.agones.dev at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io \"agones-controller\" not found","severity":"error","time":"2019-04-16T18:11:12.864170817Z"}
{"message":"agones.dev/agones/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.GameServerSet: gameserversets.stable.agones.dev is forbidden: User \"system:serviceaccount:agones-system:agones-controller\" cannot list gameserversets.stable.agones.dev at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io \"agones-controller\" not found","severity":"error","time":"2019-04-16T18:11:12.864186074Z"}
{"error":"customresourcedefinitions.apiextensions.k8s.io \"fleetautoscalers.stable.agones.dev\" is forbidden: User \"system:serviceaccount:agones-system:agones-controller\" cannot get customresourcedefinitions.apiextensions.k8s.io at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io \"agones-controller\" not found","message":"could not start runner: *fleetautoscalers.Controller","severity":"fatal","source":"main","time":"2019-04-16T18:11:12.865730852Z"}

**Comment by markmandel** [comment]
Looks like your RBAC permissions are not setup.

When you installed Agones - where there any errors? I wonder if your user had permissions to setup the service accounts?

**Comment by bramdutch0** [comment]
When I try to rerun the command to enable RBAC permissions (kubectl create clusterrolebinding cluster-admin-binding \
>   --clusterrole cluster-admin --user `gcloud config get-value account`)
I get this output:
Your active configuration is: [cloudshell-26994]
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "cluster-admin-binding" already exists

I ran the commands as they appeared in the install guide (https://agones.dev/site/docs/installation/) and 
when I run "kubectl describe --namespace agones-system pods" I get the output described in the guide. Any ideas on what I could try to fix this?

**Comment by markmandel** [comment]
Are you sharing this cluster with anyone else?

What happens if you re-apply the install.yaml?

**Comment by bramdutch0** [comment]
For now I'm just using the cluster for personal use.

Here is the output when I tried to reapply the yaml:
bjectaccessreviews selfsubjectrulesreviews] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]}] ruleResolutionErrors=[]
Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/GoogleCloudPlatform/agones/release-0.9.0/install/yaml/install.yaml": clusterroles.rbac.authorization.k8s.io "agones-sdk" is forbidden: attempt to grant extra privileges: [{[create] [] [events] [] []} {[list] [stable.agones.dev] [gameservers] [] []} {[update] [stable.agones.dev] [gameservers] [] []} {[watch] [stable.agones.dev] [gameservers] [] []}] user=&{ADutch56@gmail.com  [system:authenticated] map[user-assertion.cloud.google.com:[AKUJVpk6Onj0CBzTa+MDm14n5RQ6USPFOvcRwDHeUchMFFGZVyXtIH4q9muSlJOnttD9P0xUoSQiD5F4nz06i1iWtvXck5kTdwyh1CvKX5SCD9o1QyGyD0Ni1SdfK+FxAk1l+r7qhS0scZR2JMMOMOhA+Uk4dIZ3Y0u3baF5IYgWwM/I/DSPknPiGfidV7MOXy32YSuVNcjbH4ezr6B52XCQkdGj306R3kBzow==]]} ownerrules=[{[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]}] ruleResolutionErrors=[]

**Comment by markmandel** [comment]
Looks like there are issues with your cluster-admin role. Maybe try deleting it and re-adding it, and then try re-applying the index.yaml.

There should be no `Forbidden` items in the list.

**Comment by bramdutch0** [comment]
It turns out there was an issue with RBAC in GKE. This post helped me troubleshoot it if anyone else runs into this problem: https://github.com/coreos/prometheus-operator/issues/357

After that I got the yaml install file to run with no errors. 

When I try to create the server described in https://agones.dev/site/docs/getting-started/create-gameserver/, I am getting the following error still:
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/GoogleCloudPlatform/agones/release-0.9.0/examples/simple-udp/gameserver.yaml": Internal error occurred: failed calling admission webhook "mutations.stable.agones.dev": Post https://agones-controller-service.agones-system.svc:443/mutate?timeout=30s: no endpoints available for service "agones-controller-service"

However, I made my own yaml file specifically for my game and ran kubectl create -f <myfile>.yaml and it created it without problems, so I'm wondering if there might be an issue with the file described in the tutorial.

**Comment by bramdutch0** [comment]
Here are the controller logs now, in case they still reveal a problem:
{"filename":"/home/agones/logs/agones-controller-20190419_164907.log","message":"logging to file","numbackups":99,"severity":"info","source":"main","time":"2019-04-19T16:49:07.337494067Z"}
{"ctlConf":{"MinPort":7000,"MaxPort":8000,"SidecarImage":"gcr.io/agones-images/agones-sdk:0.9.0","SidecarCPURequest":"30m","SidecarCPULimit":"0","SdkServiceAccount":"agones-sdk","AlwaysPullSidecar":false,"PrometheusMetrics":true,"Stackdriver":false,"KeyFile":"/home/agones/certs/server.key","CertFile":"/home/agones/certs/server.crt","KubeConfig":"","GCPProjectID":"","NumWorkers":100,"APIServerSustainedQPS":400,"APIServerBurstQPS":500,"LogDir":"/home/agones/logs","LogSizeLimitMB":10000},"message":"starting gameServer operator...","severity":"info","source":"main","time":"2019-04-19T16:49:07.337872165Z","version":"0.9.0"}
ERROR: logging before flag.Parse: W0419 16:49:07.338275       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"maxPort":8000,"message":"Starting","minPort":7000,"severity":"info","source":"*gameservers.PortAllocator","time":"2019-04-19T16:49:07.341803181Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"GameServer"},"message":"Added webhook handler","op":"CREATE","path":"/mutate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.342315279Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"GameServer"},"message":"Added webhook handler","op":"CREATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.342442032Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"GameServerSet"},"message":"Added webhook handler","op":"CREATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.342787954Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"GameServerSet"},"message":"Added webhook handler","op":"UPDATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.342870456Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"Fleet"},"message":"Added webhook handler","op":"CREATE","path":"/mutate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.343200525Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"Fleet"},"message":"Added webhook handler","op":"CREATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.343414221Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"Fleet"},"message":"Added webhook handler","op":"UPDATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.343514064Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"FleetAllocation"},"message":"Added webhook handler","op":"CREATE","path":"/mutate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.343764584Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"FleetAllocation"},"message":"Added webhook handler","op":"CREATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.343854851Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"FleetAllocation"},"message":"Added webhook handler","op":"UPDATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.343977546Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"GameServerAllocation"},"message":"Added webhook handler","op":"CREATE","path":"/mutate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.344243349Z"}
{"groupKind":{"Group":"stable.agones.dev","Kind":"GameServerAllocation"},"message":"Added webhook handler","op":"UPDATE","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:07.34431978Z"}
{"message":"Starting http server...","severity":"info","source":"main","time":"2019-04-19T16:49:07.344927436Z"}
{"message":"Wait for cache sync","severity":"info","source":"*metrics.Controller","time":"2019-04-19T16:49:07.347412478Z"}
{"message":"https server started","server":{"Mux":{}},"severity":"info","source":"*https.Server","time":"2019-04-19T16:49:07.347689059Z"}
{"message":"Running","severity":"info","source":"*gameservers.PerNodeCounter","time":"2019-04-19T16:49:07.348382619Z"}
{"crd":"fleetautoscalers.stable.agones.dev","message":"custom resource definition established","severity":"info","source":"*fleetautoscalers.Controller","time":"2019-04-19T16:49:07.440459584Z"}
{"message":"Wait for cache sync","severity":"info","source":"*fleetautoscalers.Controller","time":"2019-04-19T16:49:07.440810449Z"}
{"crd":"fleets.stable.agones.dev","message":"custom resource definition established","severity":"info","source":"*fleets.Controller","time":"2019-04-19T16:49:07.453914962Z"}
{"message":"Wait for cache sync","severity":"info","source":"*fleets.Controller","time":"2019-04-19T16:49:07.454180274Z"}
{"crd":"gameserversets.stable.agones.dev","message":"custom resource definition established","severity":"info","source":"*gameserversets.Controller","time":"2019-04-19T16:49:07.454724748Z"}
{"message":"Wait for cache sync","severity":"info","source":"*gameserversets.Controller","time":"2019-04-19T16:49:07.454889282Z"}
{"crd":"gameserverallocations.stable.agones.dev","message":"custom resource definition established","severity":"info","source":"*gameserverallocations.Controller","time":"2019-04-19T16:49:07.46688928Z"}
{"message":"Wait for cache sync","severity":"info","source":"*gameserverallocations.Controller","time":"2019-04-19T16:49:07.467069119Z"}
{"crd":"fleetallocations.stable.agones.dev","message":"custom resource definition established","severity":"info","source":"*fleetallocation.Controller","time":"2019-04-19T16:49:07.467322403Z"}
{"crd":"gameservers.stable.agones.dev","message":"custom resource definition established","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:07.467831686Z"}
{"message":"Wait for cache sync","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:07.467985348Z"}
{"message":"Starting workers...","queue":"stable.agones.dev.FleetAutoscalerController","severity":"info","source":"*fleetautoscalers.Controller","time":"2019-04-19T16:49:07.544514732Z","workers":100}
{"message":"Starting workers...","queue":"stable.agones.dev.GameServerSetController","severity":"info","source":"*gameserversets.Controller","time":"2019-04-19T16:49:07.555859879Z","workers":100}
{"message":"Starting workers...","queue":"stable.agones.dev.FleetController","severity":"info","source":"*fleets.Controller","time":"2019-04-19T16:49:07.556546589Z","workers":100}
{"message":"Running","severity":"info","source":"*gameservers.PortAllocator","time":"2019-04-19T16:49:07.569750246Z"}
{"message":"Wait for cache sync","severity":"info","source":"*gameserverallocations.Controller","time":"2019-04-19T16:49:07.569987882Z"}
{"message":"Starting workers...","queue":"stable.agones.dev.GameServerAllocationController","severity":"info","source":"*gameserverallocations.Controller","time":"2019-04-19T16:49:07.670169488Z","workers":100}
{"message":"Resetting Port Allocation","severity":"info","source":"*gameservers.PortAllocator","time":"2019-04-19T16:49:07.670638514Z"}
{"message":"Starting workers...","queue":"stable.agones.dev.GameServerControllerDeletion","severity":"info","source":"*gameservers.Controller","subqueue":"deletion","time":"2019-04-19T16:49:07.671649718Z","workers":100}
{"message":"running webhook","path":"/mutate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:28.872068819Z"}
{"gs":{"kind":"GameServer","apiVersion":"stable.agones.dev/v1alpha1","metadata":{"name":"my-game-server","namespace":"default","creationTimestamp":null,"finalizers":["stable.agones.dev"]},"spec":{"container":"my-game-server-container","ports":[{"name":"default","portPolicy":"Dynamic","containerPort":7654,"protocol":"UDP"}],"health":{"periodSeconds":5,"failureThreshold":3,"initialDelaySeconds":5},"scheduling":"Packed","template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"name":"my-game-server-container","image":"gcr.io/balltestv1/ballgameserver:version1","resources":{}}]}}},"status":{"state":"PortAllocation","ports":null,"address":"","nodeName":""}},"gsKey":"default/my-game-server","message":"patch created!","patch":"[{\"op\":\"add\",\"path\":\"/metadata/finalizers\",\"value\":[\"stable.agones.dev\"]},{\"op\":\"add\",\"path\":\"/spec/container\",\"value\":\"my-game-server-container\"},{\"op\":\"add\",\"path\":\"/spec/ports/0/protocol\",\"value\":\"UDP\"},{\"op\":\"add\",\"path\":\"/spec/health\",\"value\":{\"failureThreshold\":3,\"initialDelaySeconds\":5,\"periodSeconds\":5}},{\"op\":\"add\",\"path\":\"/spec/scheduling\",\"value\":\"Packed\"},{\"op\":\"add\",\"path\":\"/spec/template/spec/containers/0/resources\",\"value\":{}},{\"op\":\"add\",\"path\":\"/spec/template/metadata\",\"value\":{\"creationTimestamp\":null}},{\"op\":\"add\",\"path\":\"/status\",\"value\":{\"address\":\"\",\"nodeName\":\"\",\"ports\":null,\"state\":\"PortAllocation\"}}]","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:28.874911866Z"}
{"message":"running webhook","path":"/validate","severity":"info","source":"*webhooks.WebHook","time":"2019-04-19T16:49:28.881373286Z"}
{"gs":{"kind":"GameServer","apiVersion":"stable.agones.dev/v1alpha1","metadata":{"name":"my-game-server","namespace":"default","uid":"190097a1-62c3-11e9-9bf4-42010a80022f","generation":1,"creationTimestamp":"2019-04-19T16:49:28Z","finalizers":["stable.agones.dev"]},"spec":{"container":"my-game-server-container","ports":[{"name":"default","portPolicy":"Dynamic","containerPort":7654,"protocol":"UDP"}],"health":{"periodSeconds":5,"failureThreshold":3,"initialDelaySeconds":5},"scheduling":"Packed","template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"name":"my-game-server-container","image":"gcr.io/balltestv1/ballgameserver:version1","resources":{}}]}}},"status":{"state":"PortAllocation","ports":null,"address":"","nodeName":""}},"gsKey":"default/my-game-server","message":"creationValidationHandler","review":{"kind":"AdmissionReview","apiVersion":"admission.k8s.io/v1beta1","request":{"uid":"1900b14b-62c3-11e9-9bf4-42010a80022f","kind":{"group":"stable.agones.dev","version":"v1alpha1","kind":"GameServer"},"resource":{"group":"stable.agones.dev","version":"v1alpha1","resource":"gameservers"},"namespace":"default","operation":"CREATE","userInfo":{"username":"ADutch56@gmail.com","groups":["system:authenticated"],"extra":{"user-assertion.cloud.google.com":["AKUJVpmo2/vT8E+5AUot9x09qUblOq1ZAL42KptOuniee5vcJap4bxbM0MzBdLETLiBLr8tCrioB44f4bd8xqThjd6ShFxpwK5F8yQIAM/LTICZUQugvXbxVh5RBEuPG0sBgitHlBhE/g9qNxlY98rOd7uOSlAal+ruFlYRuS2i5Ox2LIpV9srAwA3DULk/1/AvuVEpifVoBT4+bhRecnE1hyt3zTsMXtUIs+w=="]}},"object":{"apiVersion":"stable.agones.dev/v1alpha1","kind":"GameServer","metadata":{"creationTimestamp":"2019-04-19T16:49:28Z","finalizers":["stable.agones.dev"],"generation":1,"name":"my-game-server","namespace":"default","selfLink":"","uid":"190097a1-62c3-11e9-9bf4-42010a80022f"},"spec":{"container":"my-game-server-container","health":{"failureThreshold":3,"initialDelaySeconds":5,"periodSeconds":5},"ports":[{"containerPort":7654,"name":"default","portPolicy":"Dynamic","protocol":"UDP"}],"scheduling":"Packed","template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"image":"gcr.io/balltestv1/ballgameserver:version1","name":"my-game-server-container","resources":{}}]}}},"status":{"address":"","nodeName":"","ports":null,"state":"PortAllocation"}},"oldObject":null},"response":{"uid":"","allowed":true}},"severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:28.882081876Z"}
{"gsKey":"default/my-game-server","message":"Enqueuing","queue":"stable.agones.dev.GameServerControllerCreation","severity":"info","source":"*gameservers.Controller","subqueue":"creation","time":"2019-04-19T16:49:28.895529164Z"}
{"gsKey":"default/my-game-server","message":"Processing","queue":"stable.agones.dev.GameServerControllerCreation","severity":"info","source":"*gameservers.Controller","subqueue":"creation","time":"2019-04-19T16:49:28.916250201Z"}
{"gsKey":"default/my-game-server","message":"Synchronising","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:28.916670853Z"}
{"gs":{"metadata":{"name":"my-game-server","namespace":"default","selfLink":"/apis/stable.agones.dev/v1alpha1/namespaces/default/gameservers/my-game-server","uid":"190097a1-62c3-11e9-9bf4-42010a80022f","resourceVersion":"5653","generation":1,"creationTimestamp":"2019-04-19T16:49:28Z","finalizers":["stable.agones.dev"]},"spec":{"container":"my-game-server-container","ports":[{"name":"default","portPolicy":"Dynamic","containerPort":7654,"hostPort":7589,"protocol":"UDP"}],"health":{"periodSeconds":5,"failureThreshold":3,"initialDelaySeconds":5},"scheduling":"Packed","template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"name":"my-game-server-container","image":"gcr.io/balltestv1/ballgameserver:version1","resources":{}}]}}},"status":{"state":"Creating","ports":null,"address":"","nodeName":""}},"gsKey":"default/my-game-server","message":"Syncing Port Allocation GameServerState","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:28.916893723Z"}
{"message":"Event(v1.ObjectReference{Kind:\"GameServer\", Namespace:\"default\", Name:\"my-game-server\", UID:\"190097a1-62c3-11e9-9bf4-42010a80022f\", APIVersion:\"stable.agones.dev/v1alpha1\", ResourceVersion:\"5653\", FieldPath:\"\"}): type: 'Normal' reason: 'PortAllocation' Port allocated","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:28.918150008Z"}
{"gsKey":"default/my-game-server","message":"Enqueuing","queue":"stable.agones.dev.GameServerControllerCreation","severity":"info","source":"*gameservers.Controller","subqueue":"creation","time":"2019-04-19T16:49:28.931514468Z"}
{"gs":{"metadata":{"name":"my-game-server","namespace":"default","selfLink":"/apis/stable.agones.dev/v1alpha1/namespaces/default/gameservers/my-game-server","uid":"190097a1-62c3-11e9-9bf4-42010a80022f","resourceVersion":"5654","generation":1,"creationTimestamp":"2019-04-19T16:49:28Z","finalizers":["stable.agones.dev"]},"spec":{"container":"my-game-server-container","ports":[{"name":"default","portPolicy":"Dynamic","containerPort":7654,"hostPort":7589,"protocol":"UDP"}],"health":{"periodSeconds":5,"failureThreshold":3,"initialDelaySeconds":5},"scheduling":"Packed","template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"name":"my-game-server-container","image":"gcr.io/balltestv1/ballgameserver:version1","resources":{}}]}}},"status":{"state":"Creating","ports":null,"address":"","nodeName":""}},"gsKey":"default/my-game-server","message":"Syncing Create State","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:28.932861482Z"}
{"gs":{"metadata":{"name":"my-game-server","namespace":"default","selfLink":"/apis/stable.agones.dev/v1alpha1/namespaces/default/gameservers/my-game-server","uid":"190097a1-62c3-11e9-9bf4-42010a80022f","resourceVersion":"5654","generation":1,"creationTimestamp":"2019-04-19T16:49:28Z","annotations":{"stable.agones.dev/sdk-version":"0.9.0"},"finalizers":["stable.agones.dev"]},"spec":{"container":"my-game-server-container","ports":[{"name":"default","portPolicy":"Dynamic","containerPort":7654,"hostPort":7589,"protocol":"UDP"}],"health":{"periodSeconds":5,"failureThreshold":3,"initialDelaySeconds":5},"scheduling":"Packed","template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"name":"my-game-server-container","image":"gcr.io/balltestv1/ballgameserver:version1","resources":{}}]}}},"status":{"state":"Creating","ports":null,"address":"","nodeName":""}},"gsKey":"default/my-game-server","message":"creating Pod for GameServer","pod":{"metadata":{"name":"my-game-server","namespace":"default","creationTimestamp":null,"labels":{"stable.agones.dev/gameserver":"my-game-server","stable.agones.dev/role":"gameserver"},"annotations":{"cluster-autoscaler.kubernetes.io/safe-to-evict":"false","stable.agones.dev/container":"my-game-server-container","stable.agones.dev/sdk-version":"0.9.0"},"ownerReferences":[{"apiVersion":"stable.agones.dev/v1alpha1","kind":"GameServer","name":"my-game-server","uid":"190097a1-62c3-11e9-9bf4-42010a80022f","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"empty","emptyDir":{}}],"containers":[{"name":"my-game-server-container","image":"gcr.io/balltestv1/ballgameserver:version1","ports":[{"hostPort":7589,"containerPort":7654,"protocol":"UDP"}],"resources":{},"volumeMounts":[{"name":"empty","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"livenessProbe":{"httpGet":{"path":"/gshealthz","port":8080},"initialDelaySeconds":5,"periodSeconds":5,"failureThreshold":3}},{"name":"agones-gameserver-sidecar","image":"gcr.io/agones-images/agones-sdk:0.9.0","env":[{"name":"GAMESERVER_NAME","value":"my-game-server"},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"resources":{"requests":{"cpu":"30m"}},"livenessProbe":{"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":3,"periodSeconds":3}}],"serviceAccountName":"agones-sdk","affinity":{"podAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":100,"podAffinityTerm":{"labelSelector":{"matchLabels":{"stable.agones.dev/role":"gameserver"}},"topologyKey":"kubernetes.io/hostname"}}]}}},"status":{}},"severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:29.03363079Z"}
{"message":"Event(v1.ObjectReference{Kind:\"GameServer\", Namespace:\"default\", Name:\"my-game-server\", UID:\"190097a1-62c3-11e9-9bf4-42010a80022f\", APIVersion:\"stable.agones.dev/v1alpha1\", ResourceVersion:\"5654\", FieldPath:\"\"}): type: 'Normal' reason: 'Creating' Pod my-game-server created","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:29.056791179Z"}
{"gsKey":"default/my-game-server","message":"Enqueuing","queue":"stable.agones.dev.GameServerController","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:29.064519737Z"}
{"gsKey":"default/my-game-server","message":"Enqueuing","queue":"stable.agones.dev.GameServerController","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:29.071544043Z"}
{"gs":{"metadata":{"name":"my-game-server","namespace":"default","selfLink":"/apis/stable.agones.dev/v1alpha1/namespaces/default/gameservers/my-game-server","uid":"190097a1-62c3-11e9-9bf4-42010a80022f","resourceVersion":"5658","generation":1,"creationTimestamp":"2019-04-19T16:49:28Z","annotations":{"stable.agones.dev/sdk-version":"0.9.0"},"finalizers":["stable.agones.dev"]},"spec":{"container":"my-game-server-container","ports":[{"name":"default","portPolicy":"Dynamic","containerPort":7654,"hostPort":7589,"protocol":"UDP"}],"health":{"periodSeconds":5,"failureThreshold":3,"initialDelaySeconds":5},"scheduling":"Packed","template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"name":"my-game-server-container","image":"gcr.io/balltestv1/ballgameserver:version1","resources":{}}]}}},"status":{"state":"Starting","ports":null,"address":"","nodeName":""}},"gsKey":"default/my-game-server","message":"Syncing Starting GameServerState","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:29.07245228Z"}
{"gsKey":"default/my-game-server","message":"Enqueuing","queue":"stable.agones.dev.GameServerController","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:29.085419257Z"}
{"gsKey":"default/my-game-server","message":"Processing","queue":"stable.agones.dev.GameServerController","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:29.085864705Z"}
{"gsKey":"default/my-game-server","message":"Synchronising","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:29.08600239Z"}
{"gsKey":"default/my-game-server","message":"Processing","queue":"stable.agones.dev.GameServerControllerCreation","severity":"info","source":"*gameservers.Controller","subqueue":"creation","time":"2019-04-19T16:49:29.090295117Z"}
{"gsKey":"default/my-game-server","message":"Synchronising","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:29.090359913Z"}
{"message":"Event(v1.ObjectReference{Kind:\"GameServer\", Namespace:\"default\", Name:\"my-game-server\", UID:\"190097a1-62c3-11e9-9bf4-42010a80022f\", APIVersion:\"stable.agones.dev/v1alpha1\", ResourceVersion:\"5659\", FieldPath:\"\"}): type: 'Normal' reason: 'Scheduled' Address and port populated","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:49:29.090758447Z"}
{"gsKey":"default/my-game-server","message":"Enqueuing","queue":"stable.agones.dev.GameServerController","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:50:05.015932771Z"}
{"gsKey":"default/my-game-server","message":"Processing","queue":"stable.agones.dev.GameServerController","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:50:05.0378292Z"}
{"gsKey":"default/my-game-server","message":"Synchronising","severity":"info","source":"*gameservers.Controller","time":"2019-04-19T16:50:05.037971383Z"}

**Comment by markmandel** [comment]
I doubt there is an issue with the simple-udp example, as use it for demos and testing quite regularly. I expect your controller wasn't up yet when you pushed the yaml file.

Sounds like you have resolved the issue :+1: I'll close the issue for now. Please feel free to reopen if you deem it necessary.

**Comment by markmandel** [comment]
If you are looking for the same howto in our documentation, it is here:
https://agones.dev/site/docs/installation/#enabling-creation-of-rbac-resources

(We likely should split this up by provider to make things easier though)

**Comment by bramdutch0** [comment]
Everything seems to be working fine with the tutorial. Thanks for your help!
