### ISSUE TITLE
Some Gameservers stays in Unhealthy state (instead of being deleted)

### ISSUE THREAD

**Issue by ilkercelikyilmaz** [GoogleCloudPlatform/agones#736]
When a Gameservers/Pods are being allocated and shutdown, some servers do net get deleted and stuck in Unhealthy state. This issue surfaces after few hours of load testing (see the snapshot below).
This adversely impacts the overall performance.

![image](https://user-images.githubusercontent.com/17522001/56466143-9029b080-63c1-11e9-99f9-554ec7c5ab5a.png)

**Comment by markmandel** [comment]
Do we have an way to reproducing this int the repo? It doesn't seem to show up (afaik) in e2e tests. Maybe that something we should build a e2e test for and see if we can repro in that?

**Comment by ilkercelikyilmaz** [comment]
I have a simple  load test where I can generate this only after few hours of execution so I am not sure if we can have a E2E test that can test/validate this.
BTW, I have a fix for this which I am validating right now. I will send a PR soon.

**Comment by markmandel** [comment]
Very interested to see what the fix is!

**Comment by ilkercelikyilmaz** [comment]
Just sent a PR.

**Comment by markmandel** [comment]
@ilkercelikyilmaz I assume we can close this now?

**Comment by markmandel** [comment]
Closing. Can reopen if we need to.
