### ISSUE TITLE
Self allocation in Node.js is not supported

### ISSUE THREAD

**Issue by rorygarand** [GoogleCloudPlatform/agones#773]
**What happened**:
The underlying node api has an allocate method that is not exposed to users of the sdk.

**What you expected to happen**:
SDK users should be able to self allocate.

**How to reproduce it (as minimally and precisely as possible)**:
Attempting to use:
```
AgonesSDK.allocate();
```
would do nothing.

**Anything else we need to know?**:
I have an incoming PR to address the issue.

**Environment**:
- Agones version: <= 0.10.0-rc
- Kubernetes version (use `kubectl version`): n/a
- Cloud provider or hardware configuration: n/a
- Install method (yaml/helm): n/a
- Troubleshooting guide log(s): n/a
- Others: n/a

**Comment by rorygarand** [comment]
related PR: https://github.com/GoogleCloudPlatform/agones/pull/774/files

**Comment by markmandel** [comment]
Closing now that #774 is merged.
