### ISSUE TITLE
Request to become an Approver on Agones

### ISSUE THREAD

**Issue by ilkercelikyilmaz** [GoogleCloudPlatform/agones#796]
GitHub Username
@ilkercelikyilmaz 

- I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- I have read the contributor guide
- I am actively contributing to Agones
- I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
 - I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

Sponsors
@markmandel 
@Kuqd 

List of contributions to the Agones project
PRs reviewed / authored
- #567 
- #572 
- #583
- #740 
Issues responded to
- #536
- #543
- #573 
- #589
- #597 
- #624 
- #636
- #717
- #732 
- #736
- #783

**Comment by markmandel** [comment]
LGTM! :+1: 

@Kuqd you good too?

**Comment by Kuqd** [comment]
I'm definitively good too !

**Comment by markmandel** [comment]
DONE. :tada: Awesome!
